spring.application.name=main
spring.datasource.url=jdbc:mysql://localhost:3306/t3d_marketplace
spring.datasource.username=root
spring.datasource.password=Krish@7010
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
